/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.math;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Program#getProgram <em>Program</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Program#getExternal <em>External</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Program#getMath <em>Math</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Program</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Program</em>' attribute.
   * @see #setProgram(String)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getProgram_Program()
   * @model
   * @generated
   */
  String getProgram();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Program#getProgram <em>Program</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Program</em>' attribute.
   * @see #getProgram()
   * @generated
   */
  void setProgram(String value);

  /**
   * Returns the value of the '<em><b>External</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>External</em>' attribute.
   * @see #setExternal(String)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getProgram_External()
   * @model
   * @generated
   */
  String getExternal();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Program#getExternal <em>External</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>External</em>' attribute.
   * @see #getExternal()
   * @generated
   */
  void setExternal(String value);

  /**
   * Returns the value of the '<em><b>Math</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.math.MathExp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Math</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getProgram_Math()
   * @model containment="true"
   * @generated
   */
  EList<MathExp> getMath();

} // Program
